name: Android Build

on: workflow_dispatch

jobs:
  build:
    name: Android Build
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
         git submodule update --init --recursive
         haxelib --global install hmm
         haxelib --global run hmm setup
         haxelib run hmm install
         haxelib run lime setup
         haxelib lime rebuild cpp

      # - name: Configure Android
        # run: |
          # haxelib run lime setup -alias -y
          # haxelib run lime config ANDROID_SDK $ANDROID_HOME
          # haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          # haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          # haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -DGITHUB_BUILD

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: V-Slice Android
          path: export/release/android/bin/app/build/outputs/apk/*
          if-no-files-found: error
